# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'ZeroTier One' do
pod 'GoogleAnalytics'
pod 'CocoaLumberjack/Swift'
end

target 'libZeroTier' do

end

target 'ZeroTierPTP' do

end

target 'ZeroTier' do

end

target 'ZeroTierTests' do

end

